### ISSUE TITLE
Show env scope of created service tokens

### ISSUE THREAD

**Issue by rohan-chaturvedi** [phasehq/console#100]
## Is your feature request related to a problem?

The created service tokens only show the user that created them, and the expiry. The selected environment scope of each token should also be displayed.

## Describe the solution you'd like

Show the env scope 

## Additional context

![image](https://github.com/phasehq/console/assets/6710327/d313ca03-3d36-4980-8574-ae5eede7014d)

**Comment by amitsgh** [comment]
Subject: Request to work on issue

Dear @rohan-chaturvedi,
I'd like to work on above issue. Kindly consider assigning it to me.

Furthermore, could you please provide more details about the expected behavior and any specific requirements for displaying the environment scope? This will help me get a clear understanding of the scope of the task.

Best Regards

**Comment by rohan-chaturvedi** [comment]
Hey @amitsgh :wave: 

Here's some more context on this issue. In the console, you can create service tokens for specific apps, which are used to authenticate the CLI and get access to secrets for CI tools or production environments. These tokens must be given a specific environment scope, i.e "Development / Staging / Production". Under the app > tokens tab, if you click on "Create Service Token" you will see the following dialog: 

![image](https://github.com/phasehq/console/assets/6710327/265b9fb8-6a5d-4593-8fba-cedd8c980941)

Once the token is created, there is currently no way to see what the selected scope was. We would ideally like to display this information, so that a token scoped for production is not accidentally deleted, for example. 

Feel free to hop in our [Slack](https://slack.phase.dev) if you need further context. Looking forward to your PR!

**Comment by amitsgh** [comment]
@rohan-chaturvedi, thank you for sharing the context. I will update you on the progress and reach out when in doubt.

**Comment by nimish-ks** [comment]
https://github.com/phasehq/console/pull/112 Cheers @amitsgh 🎖️
