### ISSUE TITLE
Overlapping Icons | Windows Edge

### ISSUE THREAD

**Issue by amitsgh** [phasehq/console#102]
### Describe the bug

Overlapping icon 

### To Reproduce

1. Go to '/signup'
2. Get to the sudo password step
3. Type a sudo password
4. See that the browser draws an eye icon over the one in the UI

### Expected behavior

Only one eye icon should be displayed

### Screenshots
![image](https://github.com/phasehq/console/assets/63700757/5d8ed44a-ba5e-4d36-bfd3-7f364d9c89df)

### Platform you are having the issue on:
Browser - Windows Edge
OS - Windows

**Comment by rohan-chaturvedi** [comment]
Thanks for the bug report @amitsgh !

**Comment by rohan-chaturvedi** [comment]
@amitsgh This issue most likely exists in all parts of the UI where `input type="password"` is used. Adding this to `globals.css` might fix it:

```
::-ms-reveal {
    display: none;
}
```

Source: https://learn.microsoft.com/en-us/microsoft-edge/web-platform/password-reveal#remove-the-password-reveal-control
