### ISSUE TITLE
Add 'create organisation' button to org context switcher

### ISSUE THREAD

**Issue by nimish-ks** [phasehq/console#113]
## Is your feature request related to a problem?

Currently users need to manually visit `/signup` to create a new organisation if they are a member of an existing org. 

## Describe the solution you'd like

1. Make the organisation context switcher persistent (even when an account has a single organisation)
![image](https://github.com/phasehq/console/assets/85357445/fae0a249-9d4c-4cb5-ab3d-1c5b1e68a0d5)

2. Add a 'Create new organisation' button at the bottom of the list that will send a user to `/signup`

**Comment by amitsgh** [comment]
@rohan-chaturvedi, I'd like to work on this!!

**Comment by rohan-chaturvedi** [comment]
> @rohan-chaturvedi, I'd like to work on this!!

Assigned! Lmk if you need any additional context.

**Comment by amitsgh** [comment]
@rohan-chaturved, Sure!!
