### ISSUE TITLE
Secret naming convention: replace a space with a underscore

### ISSUE THREAD

**Issue by nimish-ks** [phasehq/console#118]
### Describe the 

Currently it is possible add a blank space while naming a key belonging to a secret. This can cause issues.
![image](https://github.com/phasehq/console/assets/85357445/d6804262-721f-4425-905a-88d6499870a2)

### Expected behavior

Don't allow blank space ' ' characters. While the user is typing a key name automatically replace each space character ' ' with an underscore '_'.

Here's a generic regex expression that is in compliance with the dotenv convention:
```
^[A-Z][A-Z0-9_]*(_[A-Z0-9]+)*$
```

https://regex101.com/r/Z6hRKv/1

**Comment by rohan-chaturvedi** [comment]
Fixed in https://github.com/phasehq/console/pull/146
