### ISSUE TITLE
Improve login screen on mobile

### ISSUE THREAD

**Issue by nimish-ks** [phasehq/console#128]
### Describe the bug

The Phase Console login screen UI is has scaling issues on mobile. 

![image](https://github.com/phasehq/console/assets/85357445/08422f59-341b-43f2-b2ae-9d7c526823b0)

### Expected behavior

Make sure the login screen is responsive on devices with smaller screens.

**Comment by teyim** [comment]
Can i work on this?

**Comment by rohan-chaturvedi** [comment]
> Can i work on this?

Hey, @teyim :wave: . Yes, feel free to pick it up!

**Comment by rohan-chaturvedi** [comment]
Fixed in #185
