### ISSUE TITLE
Improve signup UX

### ISSUE THREAD

**Issue by teyim** [phasehq/console#180]
### Current behavior
After inputing a team name in step one, the user only discovers that this team name is not available after clicking the **finish** button in step 3. This user experience is a little poor,  since the user will continuessly navigate between the first step and last step and will also have to wait for some time (depending on their network speed) in step 3 before getting that error.

### Suggested Behavior
User should see team name availability as they type in the team name. Something similar to typing in a new repo name in Github

**Comment by rohan-chaturvedi** [comment]
Fixed in #255
