### ISSUE TITLE
Modify client-side input validation 

### ISSUE THREAD

**Issue by teyim** [phasehq/console#181]
### Describe the bug
Input fields allow users to input very lengthy strings, causing the UI of the application to break. 

### To Reproduce

1. Go to Home tab on the user dashboard
2. Click on create an app
3.  Input 13+ zeros in the app name input field

### Expected behavior
The input validation should restrict the number of characters I put in the input field.

### Screenshots

![Screenshot from 2024-02-16 13-06-36](https://github.com/phasehq/console/assets/48864977/af813fb9-00eb-490b-941b-cc34336e8886)

### Platform you are having the issue on:
User Dashboard

**Comment by rohan-chaturvedi** [comment]
Good catch! Lets limit the input to something like 16 or 32 chars, and make sure longer app names wrap properly. Do you want to take this up @teyim ?

**Comment by teyim** [comment]
yes @rohan-chaturvedi . will work on this.
