### ISSUE TITLE
Add a spinner to keyring unlock button

### ISSUE THREAD

**Issue by nimish-ks** [phasehq/console#200]
On slower systems it takes a while to unlock the keyring, would be helpful to have a indicator.

[Screencast.webm](https://github.com/phasehq/console/assets/85357445/50406d1a-9a9c-4cb1-8f4f-de2c4b037aad)

**Comment by 4rjunc** [comment]
@nimish-ks If the issue #80  I mentioned in Slack is fixed. Do you think I can work on this?

**Comment by rohan-chaturvedi** [comment]
@4rjunc go for it!

**Comment by 4rjunc** [comment]
@rohan-chaturvedi The indicator mentioned in the issue I didn't get a clear idea. Does it mean adding a spinner in `Unlock` Button
<img width="523" alt="Screenshot 2024-07-27 at 19 41 45" src="https://github.com/user-attachments/assets/14670c43-5884-4802-9387-ebd70806e1b8">

**Comment by rohan-chaturvedi** [comment]
@4rjunc that's correct. I think there's already a `isLoading` prop being passed to the button, but the unlock utility runs a computationally heavy function with Argon2, and that prevents react from rendering the spinner in time. The solution might be to add a 200-300 ms timeout before calling the unlock function. Check out the implementation in the signup page, where a similar solution is used.

**Comment by nimish-ks** [comment]
thanks @4rjunc!
