### ISSUE TITLE
Speed up 'replace-variable.sh' by on running `sed` only on files with `BAKED_`

### ISSUE THREAD

**Issue by firemuzzy** [phasehq/console#203]
## Is your feature request related to a problem?

In you `replace-variable.sh` you are string replacing every `*.js` file instead of matches with `BAKED_`.
Run the output of `find` through `grep` for a significant speed up.

Thank you for your post on build one run many post. 

## Describe the solution you'd like

Pipe the output of find through grep. This way you are running `sed` only on matching files

in 

https://github.com/phasehq/console/blob/257abadd13a411c2dd627f5eb4bb5b6655f26161/frontend/scripts/replace-variable.sh#L35

change:

```bash
find /app/public /app/.next -type f -name "*.js" |
while read file; do
```

to 

```bash
find /app/public /app/.next -type f -name "*.js" | xargs grep -i -l "BAKED_" |
while read file; do
```

**Comment by rohan-chaturvedi** [comment]
Thanks a lot for the suggestion @firemuzzy ! This makes a lot of sense, will add this to our next release :+1:
