### ISSUE TITLE
Fix the temporarily Something went wrong error while accepting an org invite

### ISSUE THREAD

**Issue by nimish-ks** [phasehq/console#207]
[Screencast from 2024-03-04 14-01-20.webm](https://github.com/phasehq/console/assets/85357445/d5285044-3316-4be3-a322-f30dbd53454c)
 

![image](https://github.com/phasehq/console/assets/85357445/084aea1d-bf49-4d64-a437-03596a35076d)

**Comment by muntaxir4** [comment]
Found what's causing this bug. Can you assign me this issue @nimish-ks ?

**Comment by nimish-ks** [comment]
@muntaxir4 all yours!
