### ISSUE TITLE
show icons for third party integrations in app card

### ISSUE THREAD

**Issue by rohan-chaturvedi** [phasehq/console#260]
## Is your feature request related to a problem?

The app card currently shows no information about any integrations that might exist for the given app

![Screenshot from 2024-05-28 12-56-21](https://github.com/phasehq/console/assets/6710327/1ac99e00-4bf1-4ab3-8d7c-1afe726b59e5)

![Screenshot from 2024-05-28 12-55-45](https://github.com/phasehq/console/assets/6710327/d9fac219-1a7e-4c38-9a9c-2fb751809995)

## Describe the solution you'd like

Show a list of icons representing any thirdy party integrations that are set up for the app. The list can be truncated to 3-4 items with a `+n` for apps with several integrations 

There could also be a small count tag against each icon to denote multiple syncs for a given service, for example `gitlab (2)`, `vault`, `nomad (3)` etc

**Comment by SuryatejPonnapalli** [comment]
@rohan-chaturvedi can I take up this issue?

**Comment by rohan-chaturvedi** [comment]
Sure @SuryatejPonnapalli, it's yours!

**Comment by SuryatejPonnapalli** [comment]
@rohan-chaturvedi how do I add active syncs in syncing? I don't have any service credentials/service accounts. Is there any way so I can test it?

**Comment by rohan-chaturvedi** [comment]
> @rohan-chaturvedi how do I add active syncs in syncing? I don't have any service credentials/service accounts. Is there any way so I can test it?

Hey @SuryatejPonnapalli , you could signup with a free account for a service like Cloudflare Pages or Railway.  You could use GitHub integrations as well, but to set that up is slightly more complex. The docs should help: https://docs.phase.dev/integrations/platforms/github-actions

**Comment by SuryatejPonnapalli** [comment]
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/03fb4f1c-7902-4e36-905c-232ee4f4b208">
I've worked on this issue and come up with a solution, but I didn't use 'useState' and change the whole page to client side rendering, instead used 'let' to count the number of different providers. Should I proceed with this approach, or should I switch to using useState for counting the number of providers?

**Comment by rohan-chaturvedi** [comment]
@SuryatejPonnapalli yep, that's great!
