### ISSUE TITLE
Fix nav bar z index over the scroll bar  

### ISSUE THREAD

**Issue by nimish-ks** [phasehq/console#301]
### Describe the bug

The navigation bar renders above the scroll bar on the Phase Console home screen hiding the scroll bar up button on certain browsers.   

![image](https://github.com/user-attachments/assets/b3782688-aa7d-4500-b89d-75e32768b68d)

### To Reproduce

1. Open the Phase Console in browsers or on operating systems with wider scroll bars with scroll up and down buttons. (if you are on Linux, brave would be a good choice)
2. Log in and go to organization home
3. Look at the top right of your screen and observe that the top of the scroll bar is appearing below the status bar.
 

### Expected behavior

Fix the Z index of the status bar so that it doesn't cover the scroll bar.

**Comment by muntaxir4** [comment]
Can you assign me this issue?
