### ISSUE TITLE
Command palette (Ctrl + K)

### ISSUE THREAD

**Issue by rohan-chaturvedi** [phasehq/console#304]
## Is your feature request related to a problem?

The UI navigation for performing certain actions sometimes requires multiple clicks and page loads. 

## Describe the solution you'd like

A command palette, such as the one in Linear. Pressing `Ctrl + K` (or `⌘ + K` on Mac) should bring up a list of commands, with an autocomplete search bar. 

[Screencast from 07-26-2024 08:34:07 PM.webm](https://github.com/user-attachments/assets/66cd475f-c24b-4c8e-97f1-00fa7569c242)

The commands should include common actions, as well as navigation to resources within the current workspace:
* Create an App
* Navigate to an App
* Navigate to an Environment
* Open Integrations
* Create a new Integration
* View logs
* Invite a User
* Manage Organisation Users
* Navigate to Settings
* Toggle dark / light theme

## Additional context
A native implementation using the headlessui dialog is preferred, but an external library such as [react-cmdk](https://react-cmdk.com/) could be used as well.

**Comment by nishaaannnt** [comment]
Hello, @rohan-chaturvedi , we would like to work on this issue under Fosshack 2024. 
Me and my teammate @viku3150 are well versed with the tech stack and the codebase and hence would like to take this forward. 
Please assign us for the same. 
Thank you.

**Comment by rohan-chaturvedi** [comment]
@nishaaannnt it's all yours!

**Comment by nishaaannnt** [comment]
@rohan-chaturvedi 
![image](https://github.com/user-attachments/assets/07ba6968-aa6e-4acd-a5d4-0b75e107e4d8)

Wanted to know about the navigations. But what do you think of this right now. I researched about the CSS and found no way to change its style

**Comment by rohan-chaturvedi** [comment]
Functionality looks awesome, but not too sure about the UI. Is it feasible to use a native implementation, using either the `GenericDialog` component or atleast the headlessui Dialog with our own design language?

**Comment by nishaaannnt** [comment]
@rohan-chaturvedi maybe i will be using [this](https://main--5c34dd1c22fa8200244c31dd.chromatic.com/?path=/story/command-palette--with-a-theme) . Custom style is possible in this

**Comment by nishaaannnt** [comment]
@rohan-chaturvedi 

https://github.com/user-attachments/assets/39d2c9d2-5749-49cb-855b-e8a67238862d


1. Small ui changes are pending
2. Some functionality is pending 

Do this and let you know. But how does this look so far?

**Comment by rohan-chaturvedi** [comment]
Coming along well! We can fine tune the UI a bit once you have a PR. Check out the search on our docs for a good baseline on colors, spacing etc.

**Comment by nishaaannnt** [comment]
I think this looks better. Will start with the app navigation functionality

<img width="749" alt="Screenshot 2024-07-28 at 12 41 44 PM" src="https://github.com/user-attachments/assets/d5115936-95ad-4ad9-a6d3-c7e4dbd4940a">
<img width="739" alt="Screenshot 2024-07-28 at 12 42 00 PM" src="https://github.com/user-attachments/assets/4a374109-c7d1-41ac-981e-61ef2ed84d7e">

**Comment by nishaaannnt** [comment]
@rohan-chaturvedi 
![image](https://github.com/user-attachments/assets/326e9b91-f028-41e9-b1d8-4dd2d6823a33)
