### ISSUE TITLE
Create a development nginx config

### ISSUE THREAD

**Issue by nimish-ks** [phasehq/console#33]
Create a new nginx config that doesn't use https for local docker compose dev environment.

**Comment by Jay-Iam** [comment]
Hey Nimish, is anyone working on the issue? Else, I would like to work on in

**Comment by nimish-ks** [comment]
@Jay-Iam sure, go ahead👨‍🔧

**Comment by nimish-ks** [comment]
https://github.com/phasehq/console/pull/45 merged. 🎖️ @Jay-Iam
