### ISSUE TITLE
Fix search UI on white theme

### ISSUE THREAD

**Issue by nimish-ks** [phasehq/console#74]
Fix the white background on the magnifying glass icon and "clear search" buttons in the input box. Make them match the background color of the input field.

![image](https://github.com/phasehq/console/assets/85357445/2320e85c-486e-4390-8ae0-8e6ddf2763c5)

**Comment by amitsgh** [comment]
@nimish-ks, I'd like to work on this!

**Comment by nimish-ks** [comment]
> @nimish-ks, I'd like to work on this!

All yours buddy
