### ISSUE TITLE
Gracefully handle org level access  being revoked

### ISSUE THREAD

**Issue by nimish-ks** [phasehq/console#80]
![Screenshot from 2023-10-16 12-42-49](https://github.com/phasehq/console/assets/85357445/bed8f33c-4bfc-4242-a256-242c25e318ff)

Steps are reproduce:
1. log in to an admin / owner level access account
2. remove a user who is already logged in
3. switch to the users account and refresh the console page

**Comment by H4K3R13** [comment]
So user should be displayed something like this instead of this Application Error
![accessRevoked](https://github.com/phasehq/console/assets/50370450/a6ecb60b-c566-45da-90a8-56b73582b849)

**Comment by nimish-ks** [comment]
CC @rohan-chaturvedi

**Comment by rohan-chaturvedi** [comment]
> So user should be displayed something like this instead of this Application Error, What about this design? ![accessRevoked](https://private-user-images.githubusercontent.com/50370450/341479301-a6ecb60b-c566-45da-90a8-56b73582b849.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5MDA5MzQsIm5iZiI6MTcxODkwMDYzNCwicGF0aCI6Ii81MDM3MDQ1MC8zNDE0NzkzMDEtYTZlY2I2MGItYzU2Ni00NWRhLTkwYTgtNTZiNzM1ODJiODQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDE2MjM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkNGU3N2QzODcxODM2Y2NjOWUyMGZmMDY1MmM3YmRjMTNhZDk2NzVkN2MzM2JmMzNkYTdjYTMzYWE5Y2Y3ZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E6yz-7ZARlxUoUypm0zDJ_rTzd8eHlL3ERgVTiwwKDw)

Yep, that looks great! We could also add links to the [docs](https://docs.phase.dev/) and [community slack](https://slack.phase.dev) in case users are not sure how to proceed from this state.

**Comment by H4K3R13** [comment]
Can I work on this issue?

**Comment by rohan-chaturvedi** [comment]
Sure, its all yours!
