### ISSUE TITLE
Improve formatting of email templates

### ISSUE THREAD

**Issue by nimish-ks** [phasehq/console#81]
The Email templates need several improvements
* Make sure logo is displayed
* Improve typography / spacing / layout
* Split the header and footer into separate html files for reuse.

All email templates need a rework:
https://github.com/phasehq/console/tree/main/backend/api/templates/backend/api/email_templates

Current email look:
![image](https://github.com/phasehq/console/assets/6710327/88247245-1491-4239-a600-58bf5ae790cd)

**Comment by SaranshBangar** [comment]
@rohan-chaturvedi sir, can I work on this issue under FOSS Hack?  I can ->
1. I can replicate your designs
2. I can make and implement my own designs

**Comment by rohan-chaturvedi** [comment]
Hey @iaayushmaan and @SaranshBangar , sorry for the long delay on creating the designs for this. I've created a figma file [here](https://www.figma.com/design/rlxNzBVKjySHNkDI3XerFB/Phase-Email-Templates?node-id=102-2&t=nMv8x5S05Cc83LQ6-1) with 4 emails:
- Welcome email (new email, to be sent to users post-onboard)
- Login alert
- User invited
- User joined

Here are the designs as images as well

### Welcome email
![Welcome email](https://github.com/user-attachments/assets/82b2662c-4ac6-4cb1-b252-048d52ce9d1c)

### Login alert
![Login](https://github.com/user-attachments/assets/a4579b58-e5bd-4d47-b783-fff13e345a57)

### User invite
![User invited](https://github.com/user-attachments/assets/67055016-9a68-4b6f-9fe8-a6b5dc9f355a)

### User joined org
![User joined](https://github.com/user-attachments/assets/32aede85-47b9-41f2-bee3-30f4a1918613)
